# Signoz Helm values for local Kubernetes deployment
# This configures Signoz to work in a resource-constrained local environment

# Frontend service configuration
frontend:
  service:
    type: NodePort
    nodePort: 30000
  ingress:
    enabled: false

# Query service configuration
queryService:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ClickHouse configuration (for storing metrics and traces)
clickhouse:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

# Alert Manager configuration
alertmanager:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# OpenTelemetry Collector configuration
# Using Signoz default configuration for stability
# Custom collection is handled by separate OTEL collector in microservices-demo namespace
otelCollector:
  replicas: 1
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Kafka is not needed for small local deployments
kafka:
  enabled: false
