# Kustomization for microservices-demo with OpenTelemetry integration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo

# Base manifests from Google's microservices-demo
resources:
  - otel-configmap.yaml

# Common labels to add to all resources
commonLabels:
  project: microservices-observability
  monitoring: signoz

# Patches to add OpenTelemetry configuration to all services
patches:
  # Frontend service
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://signoz-otel-collector.signoz.svc.cluster.local:4317
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"

  # Checkout service
  - target:
      kind: Deployment
      name: checkoutservice
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://signoz-otel-collector.signoz.svc.cluster.local:4317
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
